services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./ch_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  superset:
    image: apache/superset:latest
    container_name: superset_bi
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=very_secret_key_12345
    user: "root"

    entrypoint: >
      sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname Analytics --email admin@example.com --password admin &&
        superset init &&
        /usr/bin/run-server.sh --host 0.0.0.0 --port 8088 --reload
      "
    depends_on:
      - clickhouse
